### ISSUE TITLE
Preprocessify can't get environment vars

### ISSUE THREAD

**Issue by decko** [bibliolabs/preprocessify#10]
Using preprocessify it  seems that It can't see environment variables.

If I do
```bash
$ VAR="foobar" gulp
```
where I put an @echo it returns "undefined".

It only works if I use context inside the call to processify.

**Comment by evanmuller** [comment]
Preprocessify doesn't do anything with environment variables.  It uses the context object to define preprocess variables.  If you want to use environment variables you'll have to copy the environment variables into the context object manually.  Or use it in combination with something like konfig (see the readme).

**Comment by evanmuller** [comment]
If you haven't come across this: https://github.com/motdotla/dotenv, check it out.

**Comment by decko** [comment]
It's strange because preprocess itself uses environment variables to populate the annotations inside your code during the build. I'll check the dotenv solution.
