### ISSUE TITLE
preprocessify from the command line

### ISSUE THREAD

**Issue by jonathon-love** [bibliolabs/preprocessify#6]
hi, is it possible to use preprocessify from the command line?

for example, with uglifyify you can:

    browserify -t uglifyify <source file>

with thanks

**Comment by evanmuller** [comment]
It wasn't possible, but it is now.  Preprocessify wasn't a proper transform, it was a function that returned a transform.  I've just fixed that and released version 1.0.0.

Now you can do...
`browserify -t [preprocessify --contextFile ./path/to/contextFile.json] <source file>`

See the updated readme.

Thanks for the feedback.  Let me know if that works for you.

**Comment by jonathon-love** [comment]
awesome! :)
