### ISSUE TITLE
Issues with static variables and Tsify

### ISSUE THREAD

**Issue by bigtimebuddy** [bibliolabs/preprocessify#9]
I'm also having issues with preprocessing working with tsify (TypeScript). Maybe related to #8. 

Here's the command I'm running: 

``` bash
browserify src/index.ts -o bundle.js -t [preprocessify --contextFile env/debug.json] -p [tsify --target=\"es6\"]
```

**src/index.ts**

This fails because of the way that TypeScript renders static variables (it's pulls them out and adds them after the class, taking the inline comment with it). This was give me a `string contains unbalanced delimiters` error:

``` ts
class MyClass {
   // @if DEBUG
   public static NAME:string = '';
   // @endif
}
```

This works because it's more closely resembles what TypeScript is doing after is parses the ts file. 

``` ts
class MyClass {
   public static NAME:string;
}
// @if DEBUG
MyClass.NAME = '';
// @endif
```

Other than this workaround, does anyone else have a solution? Is it possible to transform before the TypeScript gets built?

**Comment by evanmuller** [comment]
Since tsify is a plugin not a transform, I don't know now to make preprocessify run before tsify, and that's what needs to happen.  Until/unless tsify becomes a transform, I'd suggest using gulp-preprocess or preprocess.
